project:
  type: website
  output-dir: docs
  
website:
  title: "604 Teaching Demo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: 
      - icon: github
        href: 
      - icon: facebook
        href: 
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, YOUR NAME"

format:
  html:
    theme: cerulean
    toc: true

editor: source

